swagger: "2.0"
info:
  title: "Blogify API"
  description: "API for Blogify backend"
  version: "1.0.0"
host: "blogify-backend.appspot.com"
schemes:
  - "https"
paths:
  /api/posts:
    get:
      description: "Retrieve a list of posts"
      operationId: "getPosts"
      responses:
        200:
          description: "Success"